[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mo-vector"
version = "0.3.6"
description = "mo-vector support for Python"
license = {text = "MIT"}
requires-python = ">= 3.8"
dependencies = [
    "numpy"
]
